import os

ENV = os.getenv('ENV')
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')

REDIS_URL = os.getenv('REDIS_URL')
SQLALCHEMY_DATABASE_URL = os.getenv('SQLALCHEMY_DATABASE_URL')

WECHAT_ADMIN_APPID = os.getenv('WECHAT_ADMIN_APPID')
WECHAT_ADMIN_SECRET = os.getenv('WECHAT_ADMIN_SECRET')
WECHAT_BOT_TOKEN = os.getenv('WECHAT_BOT_TOKEN')

VOICE_AI_USER_ID = os.getenv('VOICE_AI_USER_ID')
VOICE_AI_API_KEY = os.getenv('VOICE_AI_API_KEY')

REDIS_KEY_PREFIX = ENV + '_'